### ISSUE TITLE
Maybe setup roles/ID via config?

### ISSUE THREAD

**Issue by mrc4tt** [SanjaySRocks/DiscordTerminal-JS#1]
https://github.com/SanjaySRocks/DiscordTerminal-JS/blob/0152fbfd853f4fb76e35253f0e3aa26876b2d55a/app.js#L13

I tried setting up this script on my RPI. But I took a deep look, your "ID" is being used, that's why "command(s)" didn't work well. =)

**Comment by SanjaySRocks** [comment]
I know that, because of testing I used my id so only I can access that
command.
You can set it to your id.

**Comment by mrc4tt** [comment]
@SanjaySRocks You should make, so it's possible to set channel ID =)

**Comment by SanjaySRocks** [comment]
Sure, I'll do that in next push.
